### ISSUE TITLE
이미지 오류 발견

### ISSUE THREAD

**Issue by hotcoa922** [suteeee/RecycleApp#4]
![image](https://user-images.githubusercontent.com/81072997/129466984-bd15e046-bf77-4aa4-8e2f-56935c4bae80.png)
확장자 문제일 것으로 보임?

**Comment by suteeee** [comment]
파일 존재하지 않음 오류인데
어디서 어떻게 하면 나오는지 알려주십셩

**Comment by hotcoa922** [comment]
해결 완료 및 어차피 추후 이미지 전부 교체해야하므로  해당 issue종료
